# Handles HTTP requests like serving web pages.
import http.server

# Adds encryption so the server can use HTTPS instead
# of HTTP.
import ssl

# If you have an existing program running on port number
# 8000, you must use a different port number for this program.
PORT = 8443

# The server will only run on your local machine and listen
# on port number 8443.
server_address = ('localhost', PORT)

# Create the server.
# The handler instructs the server on how to respond to
# requests.
httpd = http.server.HTTPServer(
    server_address,
    http.server.SimpleHTTPRequestHandler
)

# SimpleHTTPRequestHandler:
# -> Serves files from your current directory.
# -> If you open a web browser, it will show the files.

# Create a TLS conext which is the modern way of implementing HTTPS.

# TLS: Transport Layer Security secures communicaton between a
# client and a server by encrypting data integrity for the purpose
# of preventing unauthorized parties from intercepting and reading
# data during transmission.

context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)

# Load the certificate and private key.
context.load_cert_chain(
    certfile="cert.pem",
    keyfile="key.pem"
)

# Execute the following command in your terminal to create these
# files:
# openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 365 -nodes

# Wraps the server socket using TLS encryption.
httpd.socket = context.wrap_socket(
    httpd.socket,
    server_side=True
)

print(f"Serving HTTPS on port {PORT}...")

httpd.serve_forever()

# Open your web browser, and paste the following in the address
# bar:
# https://localhost:8443/

# When https is crossed in the address bar, it means that the
# connection is not fully secure.

# Browsers do not trust the certificate that was generated by
# this program using OpenSSL.