// Goal:
// Practice using filter() and reduce() together.

// Imagine you work for an online store.
// Management wants to know the total revenue generated from
// orders that are at least $100.

// First, use filter() to keep only the qualifying orders.
// Then, use reduce() to calculate the total revenue from
// those qualifying orders.

const orders = [
    {
        orderId: 101,
        customer: "Alice",
        total: 250
    },
    {
        orderId: 102,
        customer: "Bob",
        total: 45
    },
    {
        orderId: 103,
        customer: "Charlie",
        total: 180
    },
    {
        orderId: 104,
        customer: "David",
        total: 95
    },
    {
        orderId: 105,
        customer: "Rose",
        total: 320
    }
];

// filter() creates a new array containing only the orders
// whose total is at least $100.
const qualifyingOrders = orders.filter((order) => {
    return order.total >= 100;
});

// reduce() calculates the total revenue by adding together
// the total of each qualifying order.

// The accumulator stores the running total.

// currentOrder represents the current object being processed.
const totalRevenue = qualifyingOrders.reduce(
    (accumulator, currentOrder) => {
        // Return the updated running total.
        return accumulator + currentOrder.total;
    },
    0
);

// Display the qualifying orders.
console.log("Qualifying Orders:");

qualifyingOrders.forEach((order) => {
    console.log(
        `Order #${order.orderId} | ` +
        `Customer: ${order.customer} | ` +
        `Total: $${order.total}`
    );
});

console.log();

// Display the total revenue generated by the qualifying orders.
console.log(`Total Revenue: $${totalRevenue}`);